# Generated by Django 3.1.5 on 2021-01-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followed_threads',
            field=models.ManyToManyField(blank=True, related_name='following_users', to='forum.Thread'),
        ),
    ]
